spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dev
    username: db_dev_user
    password: db_dev_pass #not good practice, should be either crypted or extracted to environment variable
    platform: mysql
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: schema_db_dev.sql